### ISSUE TITLE
Encounter xyz.capybara.clamav.CommunicationException when scan file more than 25M

### ISSUE THREAD

**Issue by lqqlin** [cdarras/clamav-client#17]
Hello,
When I scan some small files(10k, 10M), the code is ok.
when I scan some large files(25M, 50M, 56M), encounter below exceptions every time. Could you please help fix it? Thanks.

2022/03/08-18:14:40 [http-nio-9200-exec-2] INFO - scan start time: 2022-03-08 10:14:40.011, fileName: test.txt, fileSize: 10
 2022/03/08-18:14:41 [http-nio-9200-exec-2] INFO - scan end time: 2022-03-08 10:14:41.433
 2022/03/08-18:14:41 [http-nio-9200-exec-2] INFO - scan succeeded
 2022/03/08-18:14:41 [http-nio-9200-exec-2] INFO  - scan start time: 2022-03-08 10:14:41.435, fileName: 25m.pdf, fileSize: 26536474
 2022/03/08-18:15:18 [http-nio-9200-exec-1] INFO  - scan end time: 2022-03-08 10:15:18.583, with exception {}
 xyz.capybara.clamav.ClamavException: xyz.capybara.clamav.CommunicationException: Error while communicating with the server
	at xyz.capybara.clamav.ClamavClient.sendCommand(ClamavClient.kt:164)
	at xyz.capybara.clamav.ClamavClient.scan(ClamavClient.kt:106)
	......
Caused by: xyz.capybara.clamav.CommunicationException: Error while communicating with the server
	at xyz.capybara.clamav.commands.scan.InStream.send(InStream.kt:50)
	at xyz.capybara.clamav.commands.scan.InStream.send(InStream.kt:14)
	at xyz.capybara.clamav.ClamavClient.sendCommand(ClamavClient.kt:160)
	... 67 common frames omitted
Caused by: java.io.IOException: ????????????????????
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at xyz.capybara.clamav.commands.scan.InStream.send(InStream.kt:39)
	... 69 common frames omitted

**Comment by cdarras** [comment]
This is due to a configuration on the daemon, not a problem with the client: https://manpages.debian.org/unstable/clamav-daemon/clamd.conf.5.en.html#StreamMaxLength
By default the stream max length is set to 25M.

**Comment by lqqlin** [comment]
Thanks, I changed the stream max length, the issue is solved.
